
give @p chestui:apple
give @p chestui:arrow_blue_down
give @p chestui:arrow_blue_left
give @p chestui:arrow_blue_right
give @p chestui:arrow_blue_up
give @p chestui:arrow_green_down
give @p chestui:arrow_green_left
give @p chestui:arrow_green_right
give @p chestui:arrow_green_up
give @p chestui:arrow_long_left
give @p chestui:arrow_long_right
give @p chestui:arrow_purple_left
give @p chestui:arrow_purple_right
give @p chestui:arrow_red_left
give @p chestui:arrow_red_right
give @p chestui:arrow_yellow_up
give @p chestui:balloon
give @p chestui:banana
give @p chestui:beer
give @p chestui:bell
give @p chestui:blue_liquid
give @p chestui:bread
give @p chestui:broccoli
give @p chestui:buck
give @p chestui:burger
give @p chestui:burrito
give @p chestui:cake
give @p chestui:car
give @p chestui:catering
give @p chestui:caution
give @p chestui:check_mark
give @p chestui:cheess
give @p chestui:chest
give @p chestui:chicken
give @p chestui:clock
give @p chestui:cloud
give @p chestui:coin
give @p chestui:compass
give @p chestui:cow
give @p chestui:crab
give @p chestui:cracked_heart
give @p chestui:crown
give @p chestui:cruelty_free
give @p chestui:cup
give @p chestui:display
give @p chestui:emerald
give @p chestui:envelope
give @p chestui:female
give @p chestui:fire
give @p chestui:fireguard
give @p chestui:fish
give @p chestui:fist
give @p chestui:flag
give @p chestui:forbidden
give @p chestui:forbidden_2
give @p chestui:fork_knife
give @p chestui:french_fries
give @p chestui:golden_cup
give @p chestui:green_liquid
give @p chestui:green_sprout
give @p chestui:half_heart
give @p chestui:heart
give @p chestui:heart_arrow
give @p chestui:honey
give @p chestui:hourglass
give @p chestui:ice_cream
give @p chestui:key
give @p chestui:key_2
give @p chestui:kings_hat
give @p chestui:lemonade
give @p chestui:lightning
give @p chestui:lock
give @p chestui:magnet
give @p chestui:male
give @p chestui:medal
give @p chestui:medal_2
give @p chestui:middle_finger
give @p chestui:mountain_top
give @p chestui:muffin
give @p chestui:noodle
give @p chestui:no_meat
give @p chestui:open_chest
give @p chestui:open_lock
give @p chestui:palm
give @p chestui:pizza
give @p chestui:plane
give @p chestui:pointing_finger
give @p chestui:police
give @p chestui:question_help
give @p chestui:recycle_arrows
give @p chestui:red_cross
give @p chestui:red_liquid
give @p chestui:ruby
give @p chestui:safe
give @p chestui:salad
give @p chestui:shield
give @p chestui:skull
give @p chestui:smartphone
give @p chestui:star
give @p chestui:stars
give @p chestui:sunglasses
give @p chestui:tea
give @p chestui:thumbs_down
give @p chestui:thumbs_up
give @p chestui:treasure_chest
give @p chestui:tree
give @p chestui:unicorn
give @p chestui:victory
give @p chestui:wall